name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        config:
          [
            { os: windows-2022, launch_command: ".\Prologue.exe" },
            { os: macos-latest, launch_command: "./Prologue" },
            { os: ubuntu-20.04, launch_command: "xvfb-run ./Prologue" },
          ]

    name: CI for ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        run: |
          cd build
          cmake --build . --config Debug

      - name: Install gnuplot and jq
        if: runner.os == 'macOS'
        run: |
          brew install gnuplot
          brew install jq

      - name: Install gnuplot, jq and xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gnuplot
          sudo apt install jq
          sudo apt install xvfb

      - name: Set dt to 0.001 and wind_speed_max to 3.0 to reduce processing time
        if: runner.os != 'Windows'
        run: |
          jq ".simulation.dt|=0.001" prologue.settings.json > tmp && mv tmp prologue.settings.json
          jq ".simulation.scatter.wind_speed_max|=3.0" prologue.settings.json > tmp && mv tmp prologue.settings.json
        working-directory: ./application

      ## Test simulations on macOS and Linux
      ## Windows cannot install the gnuplot from command line

      # Single rocket testing
      - name: "[Test] Single/Detail/Trajectry/0[m]/0[deg]"
        if: runner.os != 'Windows'
        run: echo "2" "2" "1" "0" "0" "exit" | ${{ matrix.config.launch_command }}
        working-directory: ./application

      - name: "[Test] Single/Detail/Parachute/0[m]/0[deg]"
        if: runner.os != 'Windows'
        run: echo "2" "2" "2" "0" "0" "exit" | ${{ matrix.config.launch_command }}
        working-directory: ./application

      - name: "[Test] Single/Scatter/Trajectry"
        if: runner.os != 'Windows'
        run: echo "2" "1" "1" "exit" | ${{ matrix.config.launch_command }}
        working-directory: ./application

      - name: "[Test] Single/Scatter/Parachute"
        if: runner.os != 'Windows'
        run: echo "2" "1" "2" "exit" | ${{ matrix.config.launch_command }}
        working-directory: ./application

      # Multi rocket testing (Detach mode: When burning finished)
      - name: "[Test] Multi/Detail/Trajectry/0[m]/0[deg]"
        if: runner.os != 'Windows'
        run: echo "1" "2" "1" "0" "0" "1" "exit" | ${{ matrix.config.launch_command }}
        working-directory: ./application

      #- name: "[Test] Multi/Detail/Parachute/0[m]/0[deg]"
      #  if: runner.os != 'Windows'
      #  run: echo "1" "2" "2" "0" "0" "1" "exit" | ${{ matrix.config.launch_command }}
      #  working-directory: ./application

      - name: "[Test] Multi/Scatter/Trajectry"
        if: runner.os != 'Windows'
        run: echo "1" "1" "1" "1" "exit" | ${{ matrix.config.launch_command }}
        working-directory: ./application

      #- name: "[Test] Multi/Scatter/Parachute"
      #  if: runner.os != 'Windows'
      #  run: echo "1" "1" "2" "1" "exit" | ${{ matrix.config.launch_command }}
      #  working-directory: ./application
